#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: App\Controller\TournamentController::index

signup:
  path: /sign-up
  controller: App\Controller\UserController::new